version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=seanjeev
      - MONGO_PASSWORD=mypassword
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: